# Generated by Django 5.1.15 on 2026-03-10 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_email_as_username_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushtoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
