# Generated by Django 5.1.15 on 2026-03-10 23:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_email_as_username_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="MosquePrayerTime",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("fajr_jamat", models.TimeField()),
                ("dhuhr_jamat", models.TimeField()),
                ("asr_jamat", models.TimeField()),
                ("maghrib_jamat", models.TimeField()),
                ("isha_jamat", models.TimeField()),
                ("fajr_start", models.TimeField(blank=True, null=True)),
                ("sunrise", models.TimeField(blank=True, null=True)),
                ("dhuhr_start", models.TimeField(blank=True, null=True)),
                ("asr_start", models.TimeField(blank=True, null=True)),
                ("isha_start", models.TimeField(blank=True, null=True)),
                (
                    "source_url",
                    models.URLField(
                        blank=True, help_text="URL of the PDF this was scraped from"
                    ),
                ),
                (
                    "mosque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prayer_times",
                        to="core.mosque",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("mosque", "date")},
            },
        ),
    ]
