# Generated by Django 5.1.15 on 2026-03-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_mosqueprayertime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("lesson", "Lesson"),
                    ("lecture", "Lecture"),
                    ("quran_school", "Quran School"),
                    ("youth", "Youth"),
                    ("sisters", "Sisters"),
                    ("community", "Community"),
                ],
                default="lesson",
                max_length=20,
            ),
        ),
    ]
