# Generated by Django 5.1.15 on 2026-03-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_mosqueprayertime"),
    ]

    operations = [
        # Announcement indexes
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["mosque"],
                name="core_announ_mosque__idx",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["mosque", "-published_at"],
                name="core_announ_mosque__pub_idx",
            ),
        ),
        # Event indexes
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["mosque"],
                name="core_event_mosque__idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["mosque", "event_date"],
                name="core_event_mosque__date_idx",
            ),
        ),
        # UserSubscription indexes
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["user"],
                name="core_usersub_user_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["mosque"],
                name="core_usersub_mosque_idx",
            ),
        ),
        # PushToken indexes
        migrations.AddIndex(
            model_name="pushtoken",
            index=models.Index(
                fields=["user"],
                name="core_pushtoken_user_idx",
            ),
        ),
        # MosqueAdmin indexes
        migrations.AddIndex(
            model_name="mosqueadmin",
            index=models.Index(
                fields=["user"],
                name="core_mosqueadmin_user_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mosqueadmin",
            index=models.Index(
                fields=["mosque"],
                name="core_mosqueadmin_mosque_idx",
            ),
        ),
        # MosquePrayerTime composite index
        migrations.AddIndex(
            model_name="mosqueprayertime",
            index=models.Index(
                fields=["mosque", "date"],
                name="core_prayertime_mosque_date_idx",
            ),
        ),
        # Mosque indexes
        migrations.AddIndex(
            model_name="mosque",
            index=models.Index(
                fields=["city"],
                name="core_mosque_city_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mosque",
            index=models.Index(
                fields=["country"],
                name="core_mosque_country_idx",
            ),
        ),
    ]
