# Generated by Django 5.1.15 on 2026-03-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_indexes"),
        ("core", "0005_feedback"),
    ]

    operations = []
