# Generated by Django 5.1.15 on 2026-03-16 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_merge_0004_add_indexes_0005_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_event_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("processed", models.BooleanField(default=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.RemoveIndex(
            model_name="announcement",
            name="core_announ_mosque__idx",
        ),
        migrations.RemoveIndex(
            model_name="announcement",
            name="core_announ_mosque__pub_idx",
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="core_event_mosque__idx",
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="core_event_mosque__date_idx",
        ),
        migrations.RemoveIndex(
            model_name="mosque",
            name="core_mosque_city_idx",
        ),
        migrations.RemoveIndex(
            model_name="mosque",
            name="core_mosque_country_idx",
        ),
        migrations.RemoveIndex(
            model_name="mosqueadmin",
            name="core_mosqueadmin_user_idx",
        ),
        migrations.RemoveIndex(
            model_name="mosqueadmin",
            name="core_mosqueadmin_mosque_idx",
        ),
        migrations.RemoveIndex(
            model_name="mosqueprayertime",
            name="core_prayertime_mosque_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="pushtoken",
            name="core_pushtoken_user_idx",
        ),
        migrations.RemoveIndex(
            model_name="usersubscription",
            name="core_usersub_user_idx",
        ),
        migrations.RemoveIndex(
            model_name="usersubscription",
            name="core_usersub_mosque_idx",
        ),
    ]
