# Generated by Django 5.1.15 on 2026-03-18 04:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_stripeevent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe PaymentIntent or Invoice ID",
                        max_length=255,
                    ),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=255)),
                (
                    "stripe_checkout_session_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("donor_name", models.CharField(blank=True, max_length=255)),
                ("donor_email", models.EmailField(blank=True, max_length=254)),
                ("donor_address_line1", models.CharField(blank=True, max_length=255)),
                ("donor_address_line2", models.CharField(blank=True, max_length=255)),
                ("donor_city", models.CharField(blank=True, max_length=100)),
                ("donor_postcode", models.CharField(blank=True, max_length=20)),
                (
                    "donor_country",
                    models.CharField(blank=True, default="GB", max_length=2),
                ),
                (
                    "amount_pence",
                    models.PositiveIntegerField(help_text="Donation amount in pence"),
                ),
                ("currency", models.CharField(default="gbp", max_length=3)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("one_time", "One-time"), ("monthly", "Monthly")],
                        default="one_time",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        default="stripe",
                        max_length=20,
                    ),
                ),
                (
                    "gift_aid_eligible",
                    models.BooleanField(
                        default=False,
                        help_text="Donor declared they are a UK taxpayer and want Gift Aid applied",
                    ),
                ),
                (
                    "gift_aid_amount_pence",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Reclaimable Gift Aid = 25% of donation (amount × 25/100)",
                    ),
                ),
                (
                    "donation_date",
                    models.DateField(help_text="Date the payment was received"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-donation_date", "-created"],
            },
        ),
        migrations.CreateModel(
            name="GiftAidDeclaration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "donor_name",
                    models.CharField(
                        help_text="Full name as known to HMRC", max_length=255
                    ),
                ),
                ("donor_email", models.EmailField(blank=True, max_length=254)),
                (
                    "donor_address_line1",
                    models.CharField(
                        help_text="House number/name and street", max_length=255
                    ),
                ),
                ("donor_address_line2", models.CharField(blank=True, max_length=255)),
                ("donor_city", models.CharField(blank=True, max_length=100)),
                (
                    "donor_postcode",
                    models.CharField(
                        help_text="UK postcode — required by HMRC", max_length=20
                    ),
                ),
                ("donor_country", models.CharField(default="GB", max_length=2)),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Links future Stripe payments to this declaration",
                        max_length=255,
                    ),
                ),
                (
                    "declaration_date",
                    models.DateField(help_text="Date the donor made this declaration"),
                ),
                (
                    "covers_past_donations",
                    models.BooleanField(
                        default=True, help_text="Covers donations in the past 4 years"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("cancelled", "Cancelled")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("cancelled_date", models.DateField(blank=True, null=True)),
                (
                    "charity_reference",
                    models.CharField(
                        help_text="Unique reference for this donor (e.g. GA-000001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal admin notes"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-declaration_date"],
            },
        ),
        migrations.CreateModel(
            name="GiftAidClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Claim reference (e.g. GACLAIM-2026-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(help_text="Start of the claim period"),
                ),
                ("period_end", models.DateField(help_text="End of the claim period")),
                ("total_donations_pence", models.PositiveIntegerField(default=0)),
                ("total_gift_aid_pence", models.PositiveIntegerField(default=0)),
                ("donation_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted to HMRC"),
                            ("accepted", "Accepted by HMRC"),
                            ("rejected", "Rejected by HMRC"),
                            ("partially_accepted", "Partially Accepted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_date", models.DateField(blank=True, null=True)),
                (
                    "hmrc_response",
                    models.TextField(
                        blank=True, help_text="Response from HMRC after submission"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal admin notes"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "donations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Donations included in this HMRC claim",
                        related_name="gift_aid_claims",
                        to="core.donation",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end"],
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="gift_aid_declaration",
            field=models.ForeignKey(
                blank=True,
                help_text="The Gift Aid declaration covering this donation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to="core.giftaiddeclaration",
            ),
        ),
    ]
