# Generated by Django 5.1.15 on 2026-03-18 04:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_donation_giftaid"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharityGiftAidSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "charity_name",
                    models.CharField(
                        help_text="Registered charity name as known to HMRC",
                        max_length=255,
                    ),
                ),
                (
                    "hmrc_reference",
                    models.CharField(
                        help_text="HMRC Charities reference (e.g. XR12345)",
                        max_length=20,
                    ),
                ),
                (
                    "regulator_name",
                    models.CharField(
                        default="CCEW", help_text="CCEW, OSCR, or CCNI", max_length=100
                    ),
                ),
                (
                    "regulator_number",
                    models.CharField(
                        help_text="Charity Commission registration number",
                        max_length=20,
                    ),
                ),
                (
                    "official_title",
                    models.CharField(
                        blank=True, help_text="e.g. Mr, Mrs, Dr", max_length=10
                    ),
                ),
                ("official_forename", models.CharField(max_length=100)),
                ("official_surname", models.CharField(max_length=100)),
                (
                    "official_postcode",
                    models.CharField(
                        help_text="Postcode of authorised official", max_length=20
                    ),
                ),
                ("official_phone", models.CharField(max_length=30)),
                (
                    "gateway_sender_id",
                    models.CharField(
                        blank=True,
                        help_text="HMRC Government Gateway User ID (optional — only for API submission)",
                        max_length=50,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gift Aid Settings",
                "verbose_name_plural": "Gift Aid Settings",
            },
        ),
    ]
