# Generated by Django 5.1.15 on 2026-03-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_charity_gift_aid_settings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donation",
            options={
                "ordering": ["-donation_date", "-created"],
                "permissions": [
                    (
                        "view_donation_details",
                        "Can view individual donation details and donor information",
                    )
                ],
            },
        ),
    ]
