# Generated by Django 5.1.15 on 2026-03-21 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_donation_view_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Who posted this announcement (auto-filled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="body",
            field=models.TextField(
                help_text="Full announcement text. This appears in the app feed and push notifications."
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Leave blank to keep visible indefinitely. Set a date to auto-hide after that time.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="mosque",
            field=models.ForeignKey(
                help_text="Which mosque is this announcement for?",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to="core.mosque",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="priority",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("urgent", "Urgent"),
                    ("janazah", "Janazah"),
                ],
                default="normal",
                help_text="Normal = standard feed. Urgent = highlighted alert. Janazah = funeral prayer notice with dignified styling.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(
                help_text="Short, clear title (e.g. 'Eid Prayer Time Change'). Max 255 characters.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="amount_pence",
            field=models.PositiveIntegerField(
                help_text="Donation amount in pence (e.g. 1000 = £10.00)."
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="currency",
            field=models.CharField(
                default="gbp",
                help_text="Three-letter currency code (e.g. gbp).",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donation_date",
            field=models.DateField(help_text="Date the payment was received."),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor_address_line1",
            field=models.CharField(
                blank=True, help_text="House number and street.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor_address_line2",
            field=models.CharField(
                blank=True, help_text="Second address line (optional).", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor_city",
            field=models.CharField(
                blank=True, help_text="City or town.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor_country",
            field=models.CharField(
                blank=True,
                default="GB",
                help_text="Two-letter country code (e.g. GB).",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor_email",
            field=models.EmailField(
                blank=True, help_text="Donor's email address.", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor_name",
            field=models.CharField(
                blank=True, help_text="Donor's full name.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor_postcode",
            field=models.CharField(
                blank=True, help_text="Postcode (required for Gift Aid).", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="frequency",
            field=models.CharField(
                choices=[("one_time", "One-time"), ("monthly", "Monthly")],
                default="one_time",
                help_text="One-time or monthly recurring.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="source",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cash", "Cash"),
                    ("other", "Other"),
                ],
                default="stripe",
                help_text="How the donation was received.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="stripe_checkout_session_id",
            field=models.CharField(
                blank=True, help_text="Stripe checkout session ID.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, help_text="Stripe customer ID (cus_...).", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Who created this event (auto-filled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("lesson", "Lesson"),
                    ("lecture", "Lecture"),
                    ("quran_school", "Quran School"),
                    ("youth", "Youth"),
                    ("sisters", "Sisters"),
                    ("community", "Community"),
                ],
                default="lesson",
                help_text="Lesson = study circle. Lecture = one-off talk. Youth/Sisters = targeted audience. Community = general.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Describe what the event is about, who it's for, and what to bring.",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_time",
            field=models.TimeField(
                blank=True, help_text="End time. Leave blank if unknown.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateField(
                help_text="Date of the event (or first occurrence if recurring)."
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Room or area within the mosque (e.g. 'Main Hall', 'Sisters Section').",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="mosque",
            field=models.ForeignKey(
                help_text="Which mosque is hosting this event?",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="core.mosque",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="recurring",
            field=models.CharField(
                blank=True,
                choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                help_text="Leave blank for one-off events. Select weekly or monthly for repeating events.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="speaker",
            field=models.CharField(
                blank=True,
                help_text="Name of the speaker, teacher, or instructor (if applicable).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.TimeField(help_text="Start time (e.g. 19:00 or 7:00 PM)."),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(
                help_text="Event name (e.g. 'Weekly Tafseer Class'). Max 255 characters.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="category",
            field=models.CharField(
                help_text="Area of the app (e.g. prayer times, events).", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="description",
            field=models.TextField(
                blank=True, help_text="Details of the bug or feature request."
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("acknowledged", "Acknowledged"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="new",
                help_text="Track progress: New → Acknowledged → In Progress → Resolved → Closed.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="type",
            field=models.CharField(
                choices=[
                    ("bug_report", "Bug Report"),
                    ("feature_request", "Feature Request"),
                ],
                help_text="Bug report or feature request.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who submitted this. Blank for guest submissions.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="giftaidclaim",
            name="donation_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Auto-calculated number of donations in this claim.",
            ),
        ),
        migrations.AlterField(
            model_name="giftaidclaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted to HMRC"),
                    ("accepted", "Accepted by HMRC"),
                    ("rejected", "Rejected by HMRC"),
                    ("partially_accepted", "Partially Accepted"),
                ],
                default="draft",
                help_text="Current status of the HMRC claim.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="giftaidclaim",
            name="submitted_date",
            field=models.DateField(
                blank=True, help_text="Date the claim was submitted to HMRC.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="giftaidclaim",
            name="total_donations_pence",
            field=models.PositiveIntegerField(
                default=0, help_text="Auto-calculated total donation amount."
            ),
        ),
        migrations.AlterField(
            model_name="giftaidclaim",
            name="total_gift_aid_pence",
            field=models.PositiveIntegerField(
                default=0, help_text="Auto-calculated total Gift Aid reclaimable."
            ),
        ),
        migrations.AlterField(
            model_name="giftaiddeclaration",
            name="cancelled_date",
            field=models.DateField(
                blank=True,
                help_text="Date the declaration was cancelled (if applicable).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="giftaiddeclaration",
            name="donor_address_line1",
            field=models.CharField(
                help_text="House number/name and street.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="giftaiddeclaration",
            name="donor_address_line2",
            field=models.CharField(
                blank=True, help_text="Second address line (optional).", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="giftaiddeclaration",
            name="donor_city",
            field=models.CharField(
                blank=True, help_text="City or town.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="giftaiddeclaration",
            name="donor_country",
            field=models.CharField(
                default="GB", help_text="Two-letter country code.", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="giftaiddeclaration",
            name="donor_email",
            field=models.EmailField(
                blank=True,
                help_text="Donor's email for correspondence.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="giftaiddeclaration",
            name="donor_postcode",
            field=models.CharField(
                help_text="UK postcode — required by HMRC.", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="giftaiddeclaration",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("cancelled", "Cancelled")],
                default="active",
                help_text="Active or cancelled.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="mosque",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Street address including building number",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="mosque",
            name="city",
            field=models.CharField(
                blank=True, help_text="City or town", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="mosque",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Public email address for enquiries",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="mosque",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Public phone number for the mosque",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="mosque",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Country name (e.g. United Kingdom)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="mosque",
            name="jumua_time",
            field=models.TimeField(
                blank=True, help_text="Jumu'ah (Friday) prayer time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mosque",
            name="latitude",
            field=models.FloatField(
                default=0,
                help_text="GPS latitude for prayer time calculations and nearby search",
            ),
        ),
        migrations.AlterField(
            model_name="mosque",
            name="longitude",
            field=models.FloatField(
                default=0,
                help_text="GPS longitude for prayer time calculations and nearby search",
            ),
        ),
        migrations.AlterField(
            model_name="mosque",
            name="name",
            field=models.CharField(
                help_text="Official name of the mosque", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="mosque",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo of the mosque exterior",
                upload_to="mosques/",
            ),
        ),
        migrations.AlterField(
            model_name="mosque",
            name="state",
            field=models.CharField(
                blank=True, help_text="County, state, or province", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="mosque",
            name="website",
            field=models.URLField(
                blank=True, help_text="Mosque website URL (include https://)"
            ),
        ),
        migrations.AlterField(
            model_name="mosqueadmin",
            name="mosque",
            field=models.ForeignKey(
                help_text="The mosque this person helps manage.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admins",
                to="core.mosque",
            ),
        ),
        migrations.AlterField(
            model_name="mosqueadmin",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("super_admin", "Super Admin")],
                default="admin",
                help_text="Admin = can post announcements/events. Super Admin = full management access.",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="mosqueadmin",
            name="user",
            field=models.ForeignKey(
                help_text="The user being granted admin access.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mosque_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mosqueprayertime",
            name="asr_jamat",
            field=models.TimeField(
                help_text="Asr congregation time set by the mosque."
            ),
        ),
        migrations.AlterField(
            model_name="mosqueprayertime",
            name="asr_start",
            field=models.TimeField(
                blank=True, help_text="Asr start time (from timetable PDF).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mosqueprayertime",
            name="date",
            field=models.DateField(help_text="The date these prayer times apply to."),
        ),
        migrations.AlterField(
            model_name="mosqueprayertime",
            name="dhuhr_jamat",
            field=models.TimeField(
                help_text="Dhuhr congregation time set by the mosque."
            ),
        ),
        migrations.AlterField(
            model_name="mosqueprayertime",
            name="dhuhr_start",
            field=models.TimeField(
                blank=True,
                help_text="Dhuhr start time (from timetable PDF).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mosqueprayertime",
            name="fajr_jamat",
            field=models.TimeField(
                help_text="Fajr congregation time set by the mosque."
            ),
        ),
        migrations.AlterField(
            model_name="mosqueprayertime",
            name="fajr_start",
            field=models.TimeField(
                blank=True, help_text="Fajr start time (from timetable PDF).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mosqueprayertime",
            name="isha_jamat",
            field=models.TimeField(
                help_text="Isha congregation time set by the mosque."
            ),
        ),
        migrations.AlterField(
            model_name="mosqueprayertime",
            name="isha_start",
            field=models.TimeField(
                blank=True, help_text="Isha start time (from timetable PDF).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mosqueprayertime",
            name="maghrib_jamat",
            field=models.TimeField(
                help_text="Maghrib congregation time set by the mosque."
            ),
        ),
        migrations.AlterField(
            model_name="mosqueprayertime",
            name="mosque",
            field=models.ForeignKey(
                help_text="Which mosque these prayer times are for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prayer_times",
                to="core.mosque",
            ),
        ),
        migrations.AlterField(
            model_name="mosqueprayertime",
            name="sunrise",
            field=models.TimeField(blank=True, help_text="Sunrise time.", null=True),
        ),
        migrations.AlterField(
            model_name="pushtoken",
            name="platform",
            field=models.CharField(
                choices=[("ios", "iOS"), ("android", "Android")],
                help_text="iOS or Android.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="pushtoken",
            name="token",
            field=models.CharField(
                help_text="Expo push token for this device.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="pushtoken",
            name="user",
            field=models.ForeignKey(
                help_text="The user this device token belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stripeevent",
            name="event_type",
            field=models.CharField(
                help_text="Stripe event type (e.g. checkout.session.completed).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="stripeevent",
            name="payload",
            field=models.JSONField(
                blank=True, default=dict, help_text="Raw event payload from Stripe."
            ),
        ),
        migrations.AlterField(
            model_name="stripeevent",
            name="processed",
            field=models.BooleanField(
                default=True, help_text="Whether this event has been processed."
            ),
        ),
        migrations.AlterField(
            model_name="stripeevent",
            name="stripe_event_id",
            field=models.CharField(
                db_index=True,
                help_text="Stripe event ID (e.g. evt_...).",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Used for login and notifications",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Full name as displayed in the app",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="mosque",
            field=models.ForeignKey(
                help_text="The mosque they subscribed to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribers",
                to="core.mosque",
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="notify_announcements",
            field=models.BooleanField(
                default=True, help_text="Send announcement notifications."
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="notify_events",
            field=models.BooleanField(
                default=True, help_text="Send event notifications."
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="notify_prayers",
            field=models.BooleanField(
                default=True, help_text="Send prayer time reminders."
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="prayer_reminder_minutes",
            field=models.IntegerField(
                default=15,
                help_text="How many minutes before each prayer to send the reminder (e.g. 15).",
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="user",
            field=models.ForeignKey(
                help_text="The app user who subscribed.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
