# Generated by Django 5.1.15 on 2026-03-23 06:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_add_expires_at_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mosque",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo of the mosque exterior (JPEG, PNG, or WebP, max 5 MB)",
                upload_to="mosques/",
                validators=[core.models.validate_image_file],
            ),
        ),
    ]
