# Generated by Django 5.1.15 on 2026-03-24 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_photo_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="donation_date",
            field=models.DateField(
                db_index=True, help_text="Date the payment was received."
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor_email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text="Donor's email address.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateField(
                db_index=True,
                help_text="Date of the event (or first occurrence if recurring).",
            ),
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
