# Generated by Django 5.1.15 on 2026-03-28 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_pushtoken_user_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="MixlrStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_slug",
                    models.CharField(
                        help_text="Mixlr channel slug (e.g. 'salafi-publications').",
                        max_length=100,
                    ),
                ),
                (
                    "mixlr_user_id",
                    models.IntegerField(
                        default=0,
                        help_text="Numeric Mixlr user ID (used for embed URLs).",
                    ),
                ),
                (
                    "is_live",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the channel is currently broadcasting.",
                    ),
                ),
                (
                    "broadcast_title",
                    models.CharField(
                        blank=True,
                        help_text="Title of the current or last broadcast.",
                        max_length=500,
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name of the Mixlr channel.",
                        max_length=255,
                    ),
                ),
                (
                    "channel_logo_url",
                    models.URLField(
                        blank=True, help_text="URL of the channel logo/artwork."
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        auto_now=True, help_text="When the Mixlr API was last polled."
                    ),
                ),
                (
                    "last_live_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the channel was last seen broadcasting.",
                        null=True,
                    ),
                ),
                (
                    "mosque",
                    models.OneToOneField(
                        help_text="The mosque this Mixlr channel belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mixlr_status",
                        to="core.mosque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mixlr status",
                "verbose_name_plural": "Mixlr statuses",
            },
        ),
    ]
